./" Man page for valid_plugins
.TH man 1 "26 November 2020" "1.0" "valid_plugins man page"
.SH NAME
valid_plugins -/ Returns valid plugins
.SH SYNOPSIS
valid_plugins
.SH DESCRIPTION
 This script will only return valid plugins from config file
.SH OPTIONS
valid_plugin config_file
.SH SEE ALSO
viz_pipe
.SH BUGS
No known bugs.
