.\" Man page for init_bin
.TH man 1 "11 November 2020" "1.0" "init_bin  man page"
.SH NAME
init_bin \- This script will export the PipeViz bin folder as well as the man folder to the PATH environment variable.
.SH SYNOPSIS
init_bin
.SH DESCRIPTION
init_bin will export bin and man folders to environment variable and echo success message
.SH OPTIONS
The init_bin script does not take in inputs
.SH SEE ALSO
viz_pipe
.SH BUGS
No known bugs.
