 .\" Man page for parameter_files
.TH man 1 "26 November 2020" "1.0" "parameter_files man page"
.SH NAME
parameter_files  \- This script will fetch all parameter files from a given configuration file.
.SH SYNOPSIS
paramter_files
.SH DESCRIPTION
This script will fetch all parameter files from a given configuration file. Then it will find all files that contain a line 'inputfile filename'.
.SH OPTIONS
parameter_files config_file
.SH SEE ALSO
viz_pipe
.SH BUGS
No known bugs.
