./" Man page for run_test
.TH man 1 "30 November 2020" "1.0" "run_test man page"
.SH NAME
run_tests -/ Tests viz_pipe
.SH SYNOPSIS
run_tests
.SH DESCRIPTION
 Runs viz_pipe on all directories and echos Pass or Fail on each test. To determine this, all directories must match the regex ^[0-9]{2}_.*
.SH OPTIONS
run_tests does not take in any inputs
.SH SEE ALSO
viz_pipe
.SH BUGS
No known bugs.
