./" Man page for viz_pipe
.TH man 1 "26 November 2020" "1.0" "viz_pipe man page"
.SH NAME
viz_pipe -- Generates a network visualization from a configuration file.
.SH SYNOPSIS
viz_pipe config_file [png|pdf]
.SH DESCRIPTION
 Generates a dot file from a config file.
 Has the option to generate either a pdf or png.
.SH OPTIONS
.IP png
Generates the dot file as a png.
.IP pdf
Generates the dot file as a pdf.
.SH SEE ALSO
run_tests
.SH BUGS
No known bugs.
