./" Man page for viz_pipe
.TH man 1 "26 November 2020" "1.0" "viz_pipe man page"
.SH NAME
viz_pipe -/ Generates a network visualization from a configuration file.
.SH SYNOPSIS
viz_pipe
.SH DESCRIPTION
 Generates dot file and png from config file
.SH OPTIONS
valid_plugin viz_pipe config_file [png]
.SH SEE ALSO
run_tests
.SH BUGS
No known bugs.
