name: PipeViz CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup path
      run: cd bin && . ./init_bin
    - name: Run tests
      run: |
        echo $PATH
        cd .. && run_tests
